### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by sczhang870330** [goktug97/bohb-hpo#1]
The same hyperparameter combination will appear in the same budget. Is it the reason for np.random.choice? Thanks!

**Comment by goktug97** [comment]
https://github.com/goktug97/bohb-hpo/blob/2c79d9e3d7d7182388ba196aa297257f190bb8e3/bohb/bohb.py#L118-L124
You are right, I think it shouldn't sample from the previous budget. Pushed a new commit to only sample new random configuration if there is no kde model present or if the random_percent condition is hold. Depending on the configspace size I think it is still possible to see duplicated but I think it is normal.

https://github.com/goktug97/bohb-hpo/commit/96d804e0a32481d19aa5f3c69ae10f3e1d8da9dd

**Comment by sczhang870330** [comment]
What you said is correct, and I look forward to your update! Thank you!!
