### ISSUE TITLE
check algorithm

### ISSUE THREAD

**Issue by sczhang870330** [goktug97/bohb-hpo#2]
If I understand "BOHB" correctly, is it a problem to change it like this? Because the second inner loop in HB should add Bodget to the first 1/eta hyperparameter sample of the previous loop. In this way, the modification will not be applied to the first 15% of the samples from the previous iteration

**Comment by sczhang870330** [comment]
If I understand "BOHB" correctly, is it a problem to change it like this? Because the second inner loop in HB should add Bodget to the first 15% hyperparameter sample of the previous loop. In this way, the modification will not be applied to the first 15% of the samples from the previous iteration

**Comment by sczhang870330** [comment]
According to the mnist example, this code will not update the KDEs model

**Comment by goktug97** [comment]
Sorry I couldn't understand your question. Change it how? Can you give more elaborate example?

**Comment by sczhang870330** [comment]
Because the second inner loop in HB should add Bodget to the first 1/eta hyperparameter sample of the previous loop. In this way, the modification will not be applied to the first 15% of the samples from the previous iteration

**Comment by sczhang870330** [comment]
Because the second inner loop in HB should add Bodget to the first 1/eta hyperparameter sample of the previous loop. In this way, the modification will not be applied to the first 1/eta of the samples from the previous iteration

**Comment by goktug97** [comment]
Can you write the code snippet that you are thinking what it should be

**Comment by sczhang870330** [comment]
def get_sample(self, j):
      if self.kde_good is None or np.random.random() < self.random_percent:
          if self.samples.size:
              # Return a random successful sample from the previous budget
              return self.samples[j]
          else:
              # Return a random configuration as there is no sample to choose from
              return self.configspace.sample_configuration()

**Comment by sczhang870330** [comment]
def get_sample(self, j):
        `if self.kde_good is None or np.random.random() < self.random_percent:`
            if self.samples.size:
                # Return a random successful sample from the previous budget
                return self.samples[j]
            else:
                # Return a random configuration as there is no sample to choose from
                return self.configspace.sample_configuration()

**Comment by sczhang870330** [comment]
def get_sample(self, j):
        if self.kde_good is None or np.random.random() < self.random_percent:
            if self.samples.size:
                # Return a random successful sample from the previous budget
                return self.samples[j]
            else:
                # Return a random configuration as there is no sample to choose from
                return self.configspace.sample_configuration()

**Comment by sczhang870330** [comment]
n_good = int(math.ceil(self.best_percent * len(samples)))
What does this line of code mean? Thanks

**Comment by goktug97** [comment]
Are you trying to say, "the best samples from the previous budget are discarded and shouldn't they be used in the current budget for sampling". Unfortunately it is not clear in the paper if this is the correct way or not. It only says, a random configuration is sampled if the random percent condition is hold.

**Comment by sczhang870330** [comment]
yes!! The sentence "the best samples from the previous budget are discarded and shouldn't they be used in the current budget for sampling" is my idea!! Because if the budget is very small, the algorithm should meet the traditional HYPERBAND algorithm? Want to ask you! thank you

**Comment by sczhang870330** [comment]
The sentence "the best samples from the previous budget are discarded and shouldn't they be used in the current budget for sampling" is my idea!! Because if the budget is very small (Nb small), the algorithm should meet the traditional HYPERBAND algorithm ? Want to ask you!

**Comment by sczhang870330** [comment]
And I found some errors!

**Comment by sczhang870330** [comment]
1.         best_tpe_val = np.inf
2.         # Sample from the good data
3.         for _ in range(self.n_samples):
4.             idx = np.random.randint(0, len(self.kde_good.configurations))
5.             configuration = copy.deepcopy(self.kde_good.configurations[idx])
6.             for hyperparameter, bw in zip(configuration, self.kde_good.bw):
7.                 if hyperparameter.type == cs.Type.Continuous:
8.                     value = hyperparameter.value
9.                     bw = bw * self.bw_factor
10.                     hyperparameter.value = scipy.stats.truncnorm.rvs(
11.                         -value/bw, (1-value)/bw, loc=value, scale=bw)
12.                 elif hyperparameter.type == cs.Type.Discrete:
13.                     if np.random.rand() >= (1-bw):
14.                         idx = np.random.randint(len(hyperparameter.choices))
15.                         hyperparameter.value = idx
16.                 else:
17.                     raise NotImplementedError

**Comment by sczhang870330** [comment]
best_tpe_val = np.inf
      # Sample from the good data
      for _ in range(self.n_samples):
          idx = np.random.randint(0, len(self.kde_good.configurations))
          configuration = copy.deepcopy(self.kde_good.configurations[idx])
          for hyperparameter, bw in zip(configuration, self.kde_good.bw):
              if hyperparameter.type == cs.Type.Continuous:
                  value = hyperparameter.value
                  bw = bw * self.bw_factor
                  hyperparameter.value = scipy.stats.truncnorm.rvs(
                      -value/bw, (1-value)/bw, loc=value, scale=bw)
              elif hyperparameter.type == cs.Type.Discrete:
                  if np.random.rand() >= (1-bw):
                      idx = np.random.randint(len(hyperparameter.choices))
                      hyperparameter.value = idx
              else:
                  raise NotImplementedError

**Comment by sczhang870330** [comment]
best_tpe_val = np.inf    #(Should this line of code be in this position?)
        # Sample from the good data
        for _ in range(self.n_samples):
            idx = np.random.randint(0, len(self.kde_good.configurations))
            configuration = copy.deepcopy(self.kde_good.configurations[idx])
            for hyperparameter, bw in zip(configuration, self.kde_good.bw):
                if hyperparameter.type == cs.Type.Continuous:
                    value = hyperparameter.value
                    bw = bw * self.bw_factor
                    hyperparameter.value = scipy.stats.truncnorm.rvs(
                        -value/bw, (1-value)/bw, loc=value, scale=bw)
                elif hyperparameter.type == cs.Type.Discrete:
                    if np.random.rand() >= (1-bw):
                        idx = np.random.randint(len(hyperparameter.choices))
                        hyperparameter.value = idx
                else:
                    raise NotImplementedError

**Comment by goktug97** [comment]
Yes, it should be

**Comment by goktug97** [comment]
> The sentence "the best samples from the previous budget are discarded and shouldn't they be used in the current budget for sampling" is my idea!! Because if the budget is very small (Nb small), the algorithm should meet the traditional HYPERBAND algorithm ? Want to ask you!

I have to think about this

**Comment by goktug97** [comment]
> ```
>     best_tpe_val = np.inf    #(Should this line of code be in this position?)
>     # Sample from the good data
>     for _ in range(self.n_samples):
>         idx = np.random.randint(0, len(self.kde_good.configurations))
>         configuration = copy.deepcopy(self.kde_good.configurations[idx])
>         for hyperparameter, bw in zip(configuration, self.kde_good.bw):
>             if hyperparameter.type == cs.Type.Continuous:
>                 value = hyperparameter.value
>                 bw = bw * self.bw_factor
>                 hyperparameter.value = scipy.stats.truncnorm.rvs(
>                     -value/bw, (1-value)/bw, loc=value, scale=bw)
>             elif hyperparameter.type == cs.Type.Discrete:
>                 if np.random.rand() >= (1-bw):
>                     idx = np.random.randint(len(hyperparameter.choices))
>                     hyperparameter.value = idx
>             else:
>                 raise NotImplementedError
> ```

This is fixed

**Comment by goktug97** [comment]
Decided to change it like this. It now uses the good samples from the previous budget and also prevents duplication by deleting the used sample. 
```python
            if len(self.samples):
                idx = np.random.randint(0, len(self.samples))
                sample = self.samples[idx]
                self.samples = np.delete(self.samples, idx)
                return sample
            else:
                return self.configspace.sample_configuration()
```
Commit: https://github.com/goktug97/bohb-hpo/commit/a6e6d2def28522255c3928b1374f0a92d5de1ea7
